version: "3.8"

services:
  load_balancer:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - image_service1
      - image_service2

  image_service1:
    build:
      context: .
      dockerfile: /imageservice/Dockerfile
    volumes:
      - imageservice:/app/data
    environment:
      instance: 1

  image_service2:
    build:
      context: .
      dockerfile: /imageservice/Dockerfile
    volumes:
      - imageservice:/app/data
    environment:
      instance: 2
volumes:
  imageservice:
