// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: user.proto

package userProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*UserResp, error)
	GetUserByUsername(ctx context.Context, in *GetUserByUsernameReq, opts ...grpc.CallOption) (*UserResp, error)
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error)
	GetUserPasswordById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*UserPasswordResp, error)
	GetUserPasswordByUsername(ctx context.Context, in *GetUserByUsernameReq, opts ...grpc.CallOption) (*UserPasswordResp, error)
	IncrementFollowerById(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*RelationResp, error)
	DecrementFollowerById(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*RelationResp, error)
	IncrementFollowingById(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*RelationResp, error)
	DecrementFollowingById(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*RelationResp, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*UserResp, error) {
	out := new(UserResp)
	err := c.cc.Invoke(ctx, "/library.User/GetUserById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserByUsername(ctx context.Context, in *GetUserByUsernameReq, opts ...grpc.CallOption) (*UserResp, error) {
	out := new(UserResp)
	err := c.cc.Invoke(ctx, "/library.User/GetUserByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserResp, error) {
	out := new(CreateUserResp)
	err := c.cc.Invoke(ctx, "/library.User/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserPasswordById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*UserPasswordResp, error) {
	out := new(UserPasswordResp)
	err := c.cc.Invoke(ctx, "/library.User/GetUserPasswordById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUserPasswordByUsername(ctx context.Context, in *GetUserByUsernameReq, opts ...grpc.CallOption) (*UserPasswordResp, error) {
	out := new(UserPasswordResp)
	err := c.cc.Invoke(ctx, "/library.User/GetUserPasswordByUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) IncrementFollowerById(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*RelationResp, error) {
	out := new(RelationResp)
	err := c.cc.Invoke(ctx, "/library.User/IncrementFollowerById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DecrementFollowerById(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*RelationResp, error) {
	out := new(RelationResp)
	err := c.cc.Invoke(ctx, "/library.User/DecrementFollowerById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) IncrementFollowingById(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*RelationResp, error) {
	out := new(RelationResp)
	err := c.cc.Invoke(ctx, "/library.User/IncrementFollowingById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DecrementFollowingById(ctx context.Context, in *RelationReq, opts ...grpc.CallOption) (*RelationResp, error) {
	out := new(RelationResp)
	err := c.cc.Invoke(ctx, "/library.User/DecrementFollowingById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility
type UserServer interface {
	GetUserById(context.Context, *GetUserByIdReq) (*UserResp, error)
	GetUserByUsername(context.Context, *GetUserByUsernameReq) (*UserResp, error)
	CreateUser(context.Context, *CreateUserReq) (*CreateUserResp, error)
	GetUserPasswordById(context.Context, *GetUserByIdReq) (*UserPasswordResp, error)
	GetUserPasswordByUsername(context.Context, *GetUserByUsernameReq) (*UserPasswordResp, error)
	IncrementFollowerById(context.Context, *RelationReq) (*RelationResp, error)
	DecrementFollowerById(context.Context, *RelationReq) (*RelationResp, error)
	IncrementFollowingById(context.Context, *RelationReq) (*RelationResp, error)
	DecrementFollowingById(context.Context, *RelationReq) (*RelationResp, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) GetUserById(context.Context, *GetUserByIdReq) (*UserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserById not implemented")
}
func (UnimplementedUserServer) GetUserByUsername(context.Context, *GetUserByUsernameReq) (*UserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByUsername not implemented")
}
func (UnimplementedUserServer) CreateUser(context.Context, *CreateUserReq) (*CreateUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedUserServer) GetUserPasswordById(context.Context, *GetUserByIdReq) (*UserPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPasswordById not implemented")
}
func (UnimplementedUserServer) GetUserPasswordByUsername(context.Context, *GetUserByUsernameReq) (*UserPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPasswordByUsername not implemented")
}
func (UnimplementedUserServer) IncrementFollowerById(context.Context, *RelationReq) (*RelationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementFollowerById not implemented")
}
func (UnimplementedUserServer) DecrementFollowerById(context.Context, *RelationReq) (*RelationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecrementFollowerById not implemented")
}
func (UnimplementedUserServer) IncrementFollowingById(context.Context, *RelationReq) (*RelationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementFollowingById not implemented")
}
func (UnimplementedUserServer) DecrementFollowingById(context.Context, *RelationReq) (*RelationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecrementFollowingById not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_GetUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.User/GetUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserById(ctx, req.(*GetUserByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.User/GetUserByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserByUsername(ctx, req.(*GetUserByUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.User/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateUser(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserPasswordById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserPasswordById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.User/GetUserPasswordById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserPasswordById(ctx, req.(*GetUserByIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUserPasswordByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUserPasswordByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.User/GetUserPasswordByUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUserPasswordByUsername(ctx, req.(*GetUserByUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_IncrementFollowerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).IncrementFollowerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.User/IncrementFollowerById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).IncrementFollowerById(ctx, req.(*RelationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DecrementFollowerById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DecrementFollowerById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.User/DecrementFollowerById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DecrementFollowerById(ctx, req.(*RelationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_IncrementFollowingById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).IncrementFollowingById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.User/IncrementFollowingById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).IncrementFollowingById(ctx, req.(*RelationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DecrementFollowingById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DecrementFollowingById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.User/DecrementFollowingById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DecrementFollowingById(ctx, req.(*RelationReq))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "library.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserById",
			Handler:    _User_GetUserById_Handler,
		},
		{
			MethodName: "GetUserByUsername",
			Handler:    _User_GetUserByUsername_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _User_CreateUser_Handler,
		},
		{
			MethodName: "GetUserPasswordById",
			Handler:    _User_GetUserPasswordById_Handler,
		},
		{
			MethodName: "GetUserPasswordByUsername",
			Handler:    _User_GetUserPasswordByUsername_Handler,
		},
		{
			MethodName: "IncrementFollowerById",
			Handler:    _User_IncrementFollowerById_Handler,
		},
		{
			MethodName: "DecrementFollowerById",
			Handler:    _User_DecrementFollowerById_Handler,
		},
		{
			MethodName: "IncrementFollowingById",
			Handler:    _User_IncrementFollowingById_Handler,
		},
		{
			MethodName: "DecrementFollowingById",
			Handler:    _User_DecrementFollowingById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
